# Generated by Django 4.2.6 on 2023-11-24 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_created_at_order_createdat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_type',
            new_name='deliveryType',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='full_name',
            new_name='fullName',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='payment_type',
            new_name='paymentType',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='total_cost',
            new_name='totalCost',
        ),
    ]
